config/routes.rb
Rails.application.routes.draw do

  root to: 'home#front'
  get 'posts/:id/destroy', to: 'posts#destroy', :as => :destroy_post
  get '/favorites/:favorite_id/posts/new', to: 'posts#new', :as => :new_favorite_post
  get 'friendships/:id/destroy', to: 'friendships#destroy', :as => :unfriend
  post 'add_friend', to: 'friendships#create', :as => :add_friend
  get 'requests/:id/destroy', to: 'requests#destroy', :as => :cancel_request
  post 'requests/:id/destroy', to: 'requests#destroy'
  get 'posts/:post_id/comments/:id/like', to: 'comments#like', :as => :like_comment
  get 'posts/:post_id/comments/:id/unlike', to: 'comments#unlike', :as => :unlike_comment

  get 'locations/search', to: 'locations#search', :as => :location_search

  get 'comments/:id/destroy', to: 'comments#destroy', :as => :destroy_comment

  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session_path
    post 'login' => 'devise/sessions#create', :as => :user_session_path
    get 'users/sign_out', to: 'devise/sessions#destroy'
    get 'users/index', to: 'users#index'
    get 'users/:id/profile_page', to: 'users#show', :as => :profile_page
  end

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts do
    member do
      get 'like'
      get 'unlike'
    end
  end

  resources :favorites do
    member do
      get 'like'
      get 'unlike'
    end
  end

  resources :locations
  resources :uploads
  resources :comments, only: [:create]
  resources :favorites
  resources :friendships, except: [:destroy]
  resources :requests, only: [:create]

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  has_many :users
  mount_uploader :attachment, AvatarUploader
  has_many :posts
  # has_attached_file :attachment, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/pet-community-photo.jpg"
  # validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/
  # validates_with AttachmentSizeValidator, attributes: :attachment, less_than: 5.megabytes
  acts_as_votable
  acts_as_commentable
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_favorite, only: [:show, :edit, :update, :destroy, :like]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all
    if Favorite.all.length>0
      @random_favorite = Favorite.all[rand(0..(Favorite.all.length-1))]
    end
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
    @favorites = set_favorite
    @comments = @favorite.comments
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)
    @favorite.user_id = current_user.id
    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite, notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @favorite = Favorite.find(params[:id])
    @favorite.liked_by current_user
      respond_to do |format|
        format.js { }
        format.html { redirect_to @favorite }
      end
  end

  def unlike
    @favorite = Favorite.find(params[:id])
    @favorite.downvote_by current_user
    respond_to do |format|
      format.js { }
      format.html { redirect_to @favorite }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:title, :description, :user_id, :attachment)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div id="form" class="col-md-4 inner-right-sm animated fadeInUp">
      <div class="field">
        <%= f.label :attachment %><br>
        <%= f.file_field :attachment %>
      </div>

      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>

      <div class="col-sm-8 col-sm-offset-1">
        <div class="actions">
          <%= f.submit class: 'btn btn-small' %>
        </div>
      </div>
      <%= link_to "Back", :back, class: 'btn btn-small' %>
    <% end %>
    </div>
</div>

app/views/favorites/edit.html.erb
<br>
<div class="container">
<h3>Editing Favorite</h3>

<%= render 'form' %>

</div>

app/views/favorites/index.html.erb
<!DOCTYPE html>

<html>

	<body>


		<!-- ============================================================= HEADER : END ============================================================= -->


		<!-- ============================================================= MAIN ============================================================= -->

		<main>

			<!-- ============================================================= SECTION – PORTFOLIO ============================================================= -->

			<section id="portfolio">

				<div class="container inner">
					<div class="row">
            <ul class="text-center">
              <% if @favorites.length==0 %>
              <h4>There are no favorites on your feed, why not start this whole thing? </h4>
              <% end  %>
            <a href="/favorites/new" class="btn">Create a New Favorite Community</a><br>
            </ul>
					</div><!-- /.row -->
				</div><!-- /.container -->

				<div class="container inner-bottom">
					<div class="row">
						<div class="col-sm-12 portfolio">

							<ul class="filter text-center">

								<li>Community Pages</li>
							</ul><!-- /.filter -->

							<ul class="items col-3 gap">
                <% @favorites.reverse.each do |favorite|  %>
								<li class="item thumb interactive">
									<figure>

										<div class="icon-overlay icn-link">
											<a href="/favorites/<%=favorite.id%>"><%= image_tag favorite.attachment.url(:hrect_md) %></a>
										</div><!-- /.icon-overlay -->

										<figcaption class="bordered no-top-border">
											<div class="info">
												<h4><a href="/favorites/<%=favorite.id%>"><%= favorite.title %></a></h4>
												<p>Created by <%=favorite.user.name%></p>
											</div><!-- /.info -->
										</figcaption>

									</figure>
								</li><!-- /.item -->
                <% end  %>

							</ul><!-- /.items -->

						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /.container -->
			</section>

			<!-- ============================================================= SECTION – PORTFOLIO : END ============================================================= -->

			<!-- ============================================================= SECTION – SHARE : END ============================================================= -->

		</main>

		<!-- ============================================================= MAIN : END ============================================================= -->

		<!-- ============================================================= FOOTER : END ============================================================= -->

		<!-- For demo purposes – can be removed on production : End -->
	</body>
</html>

app/views/favorites/like.js.erb
$('[href="/favorites/<%= @favorite.id %>/like"]').text("<%=@favorite.get_likes.size%>");
$('[href="/favorites/<%= @favorite.id %>/like"]').attr("href", "/favorites/<%= @favorite.id %>/unlike");

app/views/favorites/new.html.erb
<br>
<div class="container">
<h1>New Favorite</h1>

<%= render 'form' %>
</div>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>
<main>

  <div class="row">
    <div id="fav-prof-pic" class="col-md-5 text-center">
      <br>
      <%= image_tag @favorite.attachment.url(:hrect_sm) || 'pet_community_photo.png', class: 'attachment' %>
      <br><br>
      <h1><%= @favorite.title %></h1>
      <p>
        <%= @favorite.description %>
      </p>
      <%= link_to("Join this community?!", like_favorite_path) %><br>
        <%= "#{@favorite.get_likes.size} people are part of this community" %><br>
      <%= link_to("Leave Group!", unlike_favorite_path) %><br>

    </ul>


      <% if current_user.id == @favorite.user_id %>
      <%= link_to 'Edit', edit_favorite_path(@favorite), class: 'btn btn-small' %>
      <%= link_to 'Destroy', @favorite, class: 'btn btn-small', method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      <%= link_to 'Back', favorites_path, class: 'btn btn-small' %>
    </div>

    <div id='favorite-community-border' class="col-md-7">
      <br><br>
      <div class="text-center">
        <h2><strong>Community Feed</strong></h2>
        <% if current_user.voted_up_on? @favorite %>
        <%= link_to("Create a new post!", new_favorite_post_path(@favorite.id), class: "btn") %><br><br>
        <% end %>
        <% if @favorite.posts.length==0 %>
        <h4>There are no posts on this community's forum, why not start this whole thing? </h4><br>
      </div>
      <% else %>

          <% @favorite.posts.reverse.each do |post|  %>

          <% if post.attachment %>
          <div id="yehuda-dream" class="post format-image">
            <div class="date-wrapper">
              <div class="date">
                <span class="Date"><%= post.created_at.to_s.split[0] %></span>
              </div><!-- /.date -->
            </div><!-- /.date-wrapper -->
          <div class="format-wrapper">
              <%= image_tag(User.find(post.user_id).avatar.url(:thumb), class: "round-image-50" )%></i></a>
          </div><!-- /.format-wrapper -->
            <div class="post-content">
              <figure  class="icn-link post-media">
                <a href="/posts/<%=post.id%>"><%= image_tag post.attachment.url(:hrect_sm),id: "fiddlesticks"  %></a>
              </figure><!-- /.post-media -->

              <ul class="meta">
                  <li class="categories"><a href="/users/<%=post.user.id%>"><%= post.user.name %></a></li>
                  <li class="comments"><a href="/posts/<%=post.id%>"><%= post.comments.length %> Comments</a></li>
                    <% if (post.get_likes.select {|vote| vote.voter_id==current_user.id}) !=[] %>
                      <li class="likes">
                        <%= link_to("#{post.get_likes.length}", unlike_post_path(post), remote: true) %>
                      </li>
                    <% elsif (post.get_likes.select {|vote| vote.voter_id==current_user.id})==[] %>
                      <li class="likes">
                          <%= link_to("#{post.get_likes.length}", like_post_path(post), remote: true) %>
                      </li>
                    <% end %>
              </ul><!-- /.meta -->


              <div class="post-info">
              <p><%=post.content %></p>
            </div>
              <!-- button stuff -->
              <ul>
                <a href="/posts/<%=post.id%>" class="btn">Show Post</a>
              <% if current_user.id == post.user_id %>
                <a href="/posts/<%=post.id%>/edit" class="btn">Edit Post</a>
                <a href="posts/<%=post.id%>/destroy" class="btn">Delete Post</a>
              <% end %>
              </ul>

            </div><!-- /.post-content -->
          </div><!-- /.post -->

          <!-- without attachment               -->
          <% elsif !post.attachment%>

          <div class="post format-standard">

            <div class="date-wrapper">
              <div class="date">
                <span class="Date"><%= post.created_at.to_s.split[0] %></span>
              </div><!-- /.date -->
            </div><!-- /.date-wrapper -->

            <div class="format-wrapper">
              <a href="#" data-filter=".format-image"><i class="round-image-50"><%= image_tag(User.find(post.user_id).avatar.url(:thumb)) %></i></a>
            </div><!-- /.format-wrapper -->

            <div class="post-content">

              <h2 class="post-title">
                <a href="blog-post.html"> <%= User.find(post.user_id).name %> </a>
              </h2>

              <ul class="meta">
                <li class="categories"><a href="/posts/<%=post.id%>">Written Post</a></li>
                <li class="comments"><a href="/posts/<%=post.id%>"><%= post.comments.length %></a></li>
                <li class="likes"><a href="/posts/<%=post.id%>"> <%= post.get_likes.size %></a></li>
              </ul><!-- /.meta -->

              <p><%=post.content %></p>

              <ul>
                <a href="/posts/<%=post.id%>" class="btn">Show Post</a>
              <% if current_user.id == post.user_id %>
                <a href="/posts/<%=post.id%>/edit" class="btn">Edit Post</a>
                <a href="posts/<%=post.id%>/destroy" class="btn">Delete Post</a>
              <% end %>
              </ul>

            </div><!-- /.post-content -->

          </div><!-- /.post -->
          <% end  %>
          <% end %>


      <% end %>
    </div>
  </div>


</main>

app/views/favorites/unlike.js.erb
$('[href="/favorites/<%= @favorite.id %>/unlike"]').text("<%=@favorite.get_likes.size%>");
$('[href="/favorites/<%= @favorite.id %>/unlike"]').attr("href", "/favorites/<%= @favorite.id %>/like");