config/routes.rb
Rails.application.routes.draw do

  root to: 'home#front'
  get 'posts/:id/destroy', to: 'posts#destroy', :as => :destroy_post
  get '/favorites/:favorite_id/posts/new', to: 'posts#new', :as => :new_favorite_post
  get 'friendships/:id/destroy', to: 'friendships#destroy', :as => :unfriend
  post 'add_friend', to: 'friendships#create', :as => :add_friend
  get 'requests/:id/destroy', to: 'requests#destroy', :as => :cancel_request
  post 'requests/:id/destroy', to: 'requests#destroy'
  get 'posts/:post_id/comments/:id/like', to: 'comments#like', :as => :like_comment
  get 'posts/:post_id/comments/:id/unlike', to: 'comments#unlike', :as => :unlike_comment

  get 'locations/search', to: 'locations#search', :as => :location_search

  get 'comments/:id/destroy', to: 'comments#destroy', :as => :destroy_comment

  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session_path
    post 'login' => 'devise/sessions#create', :as => :user_session_path
    get 'users/sign_out', to: 'devise/sessions#destroy'
    get 'users/index', to: 'users#index'
    get 'users/:id/profile_page', to: 'users#show', :as => :profile_page
  end

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts do
    member do
      get 'like'
      get 'unlike'
    end
  end

  resources :favorites do
    member do
      get 'like'
      get 'unlike'
    end
  end

  resources :locations
  resources :uploads
  resources :comments, only: [:create]
  resources :favorites
  resources :friendships, except: [:destroy]
  resources :requests, only: [:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  acts_as_votable

  # NOTE: Comments belong to a user
  belongs_to :user
  belongs_to :post
  validates_presence_of :comment
  validates_presence_of :commentable
  validates_presence_of :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_commentable, only: [:create]
  respond_to :js

  def create
    @comment = @commentable.comments.new do |message|
      message.comment = params[:comment_text]
      message.user = current_user
    end
    @comment.save
    respond_to do |format|
      format.html {redirect_to root_path}
      format.js { }
    end
  end

  def like
    @comment = Comment.find(params[:id])
    if @comment.liked_by current_user
      respond_to do |format|
        format.js {render 'comments/like.js.erb'}
        format.html { redirect_to :back }
      end
    end
  end

  # def like
  #   @post = Post.find(params[:id])
  #   @post.liked_by current_user
  #   redirect_to @post
  # end

  def unlike
    @comment = Comment.find(params[:id])
    if @comment.downvote_by current_user
      respond_to do |format|
        format.js {render 'comments/unlike.js.erb'}
        format.html { redirect_to :back }
      end
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @commentable = @comment.commentable_type.constantize.find(@comment.commentable_id)
    @comment_id = params[:id]
    @comment.destroy
      respond_to do |format|
        format.js { render 'comments/destroy.js.erb'}
        format.html {redirect_to root_path}
    end
  end

  def update
  end

  private

  def find_commentable
    @commentable_type = params[:commentable_type].classify
      if params[:commentable_id] != nil || params.include?(:post_id) == false
        @commentable = @commentable_type.constantize.find(params[:commentable_id])
      else
        @commentable = @commentable_type.constantize.find(params[:post_id])
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<br>
<style></style>
<li class="comment-<%=comment.id%>">
  <div class="avatar icon-overlay icn-link">
    <a href="/users/<%= comment.user.id%>"><%= image_tag(User.find(comment.user.id).avatar.url(:thumb)) %></a>
  </div><!-- /.avatar -->

  <div class="commentbody animated fadeInUp">

    <div class="author">
      <h3><a href="#"><%= comment.user.name %></a></h3>
      <div class="meta">
        <span class="date"><%= comment.created_at %></span>
      </div><!-- /.meta -->
    </div><!-- /.author -->

    <div id='all-comment' class="message">
      <p><%= comment.comment %></p>
      <br>
    <div class="row">
        <ul class="meta">
          <div class="col-md-2" id="column-<%= comment.id %>">
            <% if (comment.get_likes.select {|vote| vote.voter_id==current_user.id}) !=[] %>
              <li class="noAnimation">
                <%= link_to("#{comment.get_likes.length} Likes", "/posts/#{comment.commentable_id}/comments/#{comment.id}/unlike", remote: true, class: "like-#{comment.id} gray-text") %>
              </li>
            <% elsif (comment.get_likes.select {|vote| vote.voter_id==current_user.id})==[] %>
              <li class="noAnimation">
                <%= link_to("#{comment.get_likes.length} Likes", "/posts/#{comment.commentable_id}/comments/#{comment.id}/like", remote: true, class: "like-#{comment.id} gray-text") %>
              </li>
            <% end %>
          </div>

            <div class="col-md-2 col-md-offset-7" id="animator-<%= comment.id %>">
              <% if comment.user.id == current_user.id %>
              <%= link_to("Delete", destroy_comment_path(comment.id), remote: true, class: "noAnimation btn btn-sm") %>
              <% end %>
            </div>
        </ul><!-- /.meta -->
      </div>
    </div><!-- /.message -->
    <br>
  </div><!-- /.commentbody -->
</li><!-- /.comment -->

app/views/comments/_form.html.erb
<%= form_tag comments_path(commentable_type: commentable.class.to_s, commentable_id: commentable.id), method: :post, remote: true do %>
  <div class="form-group">
    <%= text_area_tag :comment_text, nil, placeholder: 'Enter Comment', class: 'form-control' %>
  </div>
  <%= submit_tag :comment, class: 'btn btn-medium' %>
<% end %>

app/views/comments/create.js.erb
 var comment_placement = $('#comments h4').first();
 $("<%=j render(@comment) %>").insertAfter(comment_placement);
 $('#comment_text').closest('form').find("input[type=text], textarea").val("");
 $('#animator-<%=@comment.id%>').addClass('animated fadeInUp');
 $('#column-<%=@comment.id%>').addClass('animated fadeInUp');
 if (<%= @commentable.comments.length %> > 1) {
   $('#comments h4').first().text("<%= @commentable.comments.length %> Comments");
   $('.comments a').text("<%= @commentable.comments.length %> Comments");
   }
 else if (<%= @commentable.comments.length %> === 1) {
   $('#comments h4').first().text("<%= @commentable.comments.length %> Comment");
   $('.comments a').text("<%= @commentable.comments.length %> Comment");
  } else {
    $('#comments h').first().text("Bark Away!");
    $('.comments a').text("No Comments");
  };

app/views/comments/destroy.js.erb
$(".comment-<%= @comment_id %>").remove();
if (<%= @commentable.comments.length %> > 1) {
  $('#comments h4').first().text("<%= @commentable.comments.length %> Comments");
  $('.comments a').text("<%= @commentable.comments.length %> Comments");
  }
else if (<%= @commentable.comments.length %> === 1) {
  $('#comments h4').first().text("<%= @commentable.comments.length %> Comment");
  $('.comments a').text("<%= @commentable.comments.length %> Comment");
 } else {
   $('#comments h4').first().text("Bark Away!");
   $('.comments a').text("No Comments");
 };

app/views/comments/like.js.erb
<% if @comment.get_likes.length == 1 %>
  $('.like-<%=@comment.id%>').text('<%=@comment.get_likes.length%> Like');
<% else %>
  $('.like-<%=@comment.id%>').text('<%=@comment.get_likes.length%> Likes');
<% end %>
  $('.like-<%=@comment.id%>').attr("href", "/posts/<%=@comment.commentable_id%>/comments/<%=@comment.id%>/unlike");

app/views/comments/unlike.js.erb
<% if @comment.get_likes.length == 1 %>
  $('.like-<%=@comment.id%>').text('<%=@comment.get_likes.length%> Like');
<% else %>
  $('.like-<%=@comment.id%>').text('<%=@comment.get_likes.length%> Likes');
<% end %>
  $('.like-<%=@comment.id%>').attr("href", "/posts/<%=@comment.commentable_id%>/comments/<%=@comment.id%>/like");