config/routes.rb
Rails.application.routes.draw do

  root to: 'home#front'
  get 'posts/:id/destroy', to: 'posts#destroy', :as => :destroy_post
  get '/favorites/:favorite_id/posts/new', to: 'posts#new', :as => :new_favorite_post
  get 'friendships/:id/destroy', to: 'friendships#destroy', :as => :unfriend
  post 'add_friend', to: 'friendships#create', :as => :add_friend
  get 'requests/:id/destroy', to: 'requests#destroy', :as => :cancel_request
  post 'requests/:id/destroy', to: 'requests#destroy'
  get 'posts/:post_id/comments/:id/like', to: 'comments#like', :as => :like_comment
  get 'posts/:post_id/comments/:id/unlike', to: 'comments#unlike', :as => :unlike_comment

  get 'locations/search', to: 'locations#search', :as => :location_search

  get 'comments/:id/destroy', to: 'comments#destroy', :as => :destroy_comment

  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session_path
    post 'login' => 'devise/sessions#create', :as => :user_session_path
    get 'users/sign_out', to: 'devise/sessions#destroy'
    get 'users/index', to: 'users#index'
    get 'users/:id/profile_page', to: 'users#show', :as => :profile_page
  end

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts do
    member do
      get 'like'
      get 'unlike'
    end
  end

  resources :favorites do
    member do
      get 'like'
      get 'unlike'
    end
  end

  resources :locations
  resources :uploads
  resources :comments, only: [:create]
  resources :favorites
  resources :friendships, except: [:destroy]
  resources :requests, only: [:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  acts_as_votable

  # NOTE: Comments belong to a user
  belongs_to :user
  belongs_to :post
  validates_presence_of :comment
  validates_presence_of :commentable
  validates_presence_of :user
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  has_many :users
  mount_uploader :attachment, AvatarUploader
  has_many :posts
  # has_attached_file :attachment, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/pet-community-photo.jpg"
  # validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/
  # validates_with AttachmentSizeValidator, attributes: :attachment, less_than: 5.megabytes
  acts_as_votable
  acts_as_commentable
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :user_locations
  has_many :users, through: :user_locations
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  mount_uploader :attachment, AvatarUploader
  acts_as_commentable
  acts_as_votable

  @@attached_photos=[]

  # def attachments(id_num,attachment)
  #   @@attached_photos << attachment
  #   photos = Hash.new
  #   photos[id_num]={attachments: @@attached_photos}
  #   photos
  # end
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  mount_uploader :name, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments
  has_many :requests
  #creates friendship relationship
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :favorites
  #creates inverse friendship relationship
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  #user location joint table relationship
  has_many :user_locations
  has_many :locations, through: :user_locations

  has_attached_file :avatar, styles: { small: "200x200>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/pet-default.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 5.megabytes

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  acts_as_voter


  @@photo_array=[]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.avatar = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def all_photos
    self.posts.each do |post|
      if post.attachment.present?
        @@photo_array=post.attachment
      end
      @@photo_array
    end
  end

  def display_photos
    all_photos.reverse
  end

  def my_friends
    friends = []
    self.friends.each do |friend|
      friends << friend
    end
    self.inverse_friends.each do |friend|
      friends << friend
    end
    friends
  end

  def find_friendship(unfriender, friend)
    Friendship.all.each do |friendship|
      if (friendship.user_id == friend.id && friendship.friend_id == unfriender.id) || (friendship.user_id == unfriender.id && friendship.friend_id == friend.id)
        my_friendship = friendship
        return my_friendship
      end
    end
  end

end

app/models/user_location.rb
class UserLocation < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def front
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def belongs_to_user?(resource)
    resource.user == current_user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_actions.html.erb
<% if user_signed_in? %>
  <div class="actions">
    <div class="row">
      <div class="col-xs-6 like">
        
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-fixed-top">

				<div class="navbar-header">
					<div class="container">

						<!-- ============================================================= LOGO MOBILE : END ============================================================= -->

						<a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i class='icon-menu-1'></i></a>

					</div><!-- /.container -->
				</div><!-- /.navbar-header -->

				<div class="yamm">
					<div class="navbar-collapse collapse">
						<div class="container">
							<a class="navbar-brand" href="/"><img src="<%= asset_path("petpal_logo2.png") %>" class="logo"></a>
							<br>

							<!-- ============================================================= MAIN NAVIGATION ============================================================= -->

						<ul class="nav navbar-nav">
              <% if !!current_user %>
								<li>
                  <%= link_to('My Profile', "/users/#{current_user.id}/profile_page") %>
								</li><!-- /.dropdown -->

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle js-activated">Friends</a>
                  <ul class="dropdown-menu">
                    <% Request.all.each do |request| %>
                    <% if request.friend_id == current_user.id %>
                    <li>   <%= "#{User.find(request.user_id).name} would like to be your friend" %>
     <%= form_for :friendship, url: add_friend_path do |f| %>
       <%= f.hidden_field :friend_id, :value => request.user_id %>
       <%= f.hidden_field :user_id, :value => request.friend_id %>
       <%= f.hidden_field :request_id, :value => request.id %>
       <%= f.submit "Accept", class: 'btn btn-small' %>
       <% end %>
   <% end %>
    <% end %>

       				</li>


         				<li>
                  <%= link_to('Add Friends', users_index_path) %>
                </li><!-- /.dropdown -->
                  </ul>
                </li><!-- /.dropdown -->

                <li>
									<%= link_to('Favorite Communities', favorites_path) %>
								</li><!-- /.dropdown -->

                <li>
									<%= link_to('News Feed', posts_path) %>
								</li><!-- /.dropdown -->

								<li class="dropdown">
                  <a href="#" class="dropdown-toggle js-activated">Hangouts</a>
                  <ul class="dropdown-menu">
										<li>
											<%= link_to('Add Hangouts', new_location_path) %>
                		</li><!-- /.dropdown -->
										<li>
											<%= link_to('Search Pals', location_search_path) %>
                		</li><!-- /.dropdown -->
										<li>
											<%= link_to('View My Hangouts', locations_path) %>
										</li><!-- /.dropdown -->
                  </ul>
                </li><!-- /.dropdown -->

                <li>
									<%= link_to('Sign Out', destroy_user_session_path) %>
								</li><!-- /.dropdown -->
                <li><%= image_tag(current_user.avatar.url(:thumb), class: "round-image-50")  %></li>

              <% else %>
              <li>
                <%= link_to "PetPal", root_url %>
              </li>
                <li>
                  <%= link_to 'Sign up', '/users/sign_up' %>
                </li><!-- /.dropdown -->

                <li>
                  <%= link_to 'Sign in', user_session_path %>
                </li><!-- /.dropdown -->

                <li>
                  <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
                </li><!-- /.dropdown -->
                  <% end %>



								<li class="dropdown pull-right searchbox">
									<a href="#" class="dropdown-toggle js-activated"><i class="icon-search"></i></a>

									<div class="dropdown-menu">
										<form id="search" class="navbar-form search" role="search">
											<input type="search" class="form-control" placeholder="Type to search">
											<button type="submit" class="btn btn-default btn-submit icon-right-open"></button>
										</form>
									</div><!-- /.dropdown-menu -->
								</li><!-- /.searchbox -->

							</ul><!-- /.nav -->

							<!-- ============================================================= MAIN NAVIGATION : END ============================================================= -->

						</div><!-- /.container -->
					</div><!-- /.navbar-collapse -->
				</div><!-- /.yamm -->
			</div><!-- /.navbar -->

app/views/user_notifier/send_signup_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome</title>
  </head>
  <body>
    <h1>Thanks for signing up, <%= @user.name %>!</h1>
    <p>Thanks for joining and have a great day! Now sign in and do
awesome things!</p>
  </body>
</html>